keys:
  - &admin age1rmaj7ayhvw9l8qtg6p9y8n8elt6xt6l7ng6suqvxsszlc83ycclspesfzc

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
        - *admin
  - path_regex: secrets/.*\.enc$
    key_groups:
      - age:
        - *admin
